### ISSUE TITLE
parse_data will create an ip out of anything

### ISSUE THREAD

**Issue by masukomi** [ipaddress2-gem/ipaddress_2#33]
## Expected behavior:
Only real ip addresses should ever be decodable into an IPAddress object. Decoding invalid strings should result in an exception being thrown.

## Actual behavior
Any random string can be parsed into a valid ipv4 or ipv6 address without error.

for example

```
IPAddress::IPv4::parse_data 'this is a bogus potato not an ip'
=> #<IPAddress::IPv4:0x00007fe271096bd0 @address="116.104.105.115", @prefix=32, @octets=[116, 104, 105, 115], @u32=1952999795, @allocator=0>
```

**Comment by Adam21e** [comment]
Good catch. I see that it was designed to work with binary data.

Are you able to submit a pull request?

**Comment by Adam21e** [comment]
closing as stale.
